# Generated by Django 6.0 on 2025-12-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('station_name', models.CharField(max_length=100)),
                ('station_code', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
