# Generated by Django 6.0 on 2025-12-22 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0002_tbl_restaurant'),
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('delivery_time', models.TimeField()),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.tbl_food')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
