# Generated by Django 6.0 on 2025-12-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tbl_booking',
            name='delivery_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tbl_booking',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
