# Generated by Django 6.0 on 2025-12-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_tbl_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='delivery_time',
            field=models.TimeField(),
        ),
    ]
