# Generated by Django 6.0 on 2025-12-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_tbl_booking_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
